[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = 
	madhephaestus/ESP32Servo@^3.2.1
	bblanchon/ArduinoJson@^7.4.3
	mathieucarbou/ESPAsyncWebServer@^3.6.0
